import Navbar from "@/components/Navbar";
import "./globals.css";
import { ThemeProvider } from "@/components/themeprovider";
import { AuthProvider } from "@/context/AuthContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className="h-screen gap-4 flex flex-col">
        <AuthProvider>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <div className="px-8">{children}</div>
          </ThemeProvider>
          </AuthProvider>
        </body>
    </html>
  );
}